---

- import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup|bool and ilmo_enabled|bool"
  tags:
    - setup-all
    - setup-ilmo

- import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: "run_setup|bool and ilmo_enabled|bool"
  tags:
    - setup-all
    - setup-ilmo

- import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: "run_setup|bool and not ilmo_enabled|bool"
  tags:
    - setup-all
    - setup-ilmo
