---

- set_fact:
    ilmo_requires_restart: false

- name: Create group
  group:
    name: "{{ ilmo_group }}"
    state: present

- name: Create user
  user:
    name: "{{ ilmo_user }}"
    group: "{{ ilmo_group }}"
    create_home: yes
    home: "{{ ilmo_base_path }}"
    shell: "/bin/bash"

- name: Ensure ilmo paths exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ ilmo_user }}"
    group: "{{ ilmo_group }}"
  with_items:
    - {path: "{{ ilmo_config_path }}", when: true}
    - {path: "{{ ilmo_data_path }}", when: true}
  when: "item.when|bool"

- name: Ensure ilmo config for sqlite3 is installed
  template:
    src: "{{ role_path }}/templates/ilmo_sqlite.cfg.j2"
    dest: "{{ ilmo_config_file }}"
    mode: 0644
    owner: "{{ ilmo_user }}"
    group: "{{ ilmo_group }}"
  when: ilmo_database_backend == "sqlite3"

- name: Ensure ilmo config for postgresql installed
  template:
    src: "{{ role_path }}/templates/ilmo_postgres.cfg.j2"
    dest: "{{ ilmo_config_file }}"
    mode: 0644
    owner: "{{ ilmo_user }}"
    group: "{{ ilmo_group }}"
  when: ilmo_database_backend == "postgresql"


- name: Ensure ilmo service installed
  template:
    src: "{{ role_path }}/templates/systemd/ilmo-web.service.j2"
    dest: "{{ ilmo_systemd_path }}/{{ ilmo_web_service_name }}"
    mode: 0644
  register: ilmo_systemd_service_result

- name: Ensure pip is on the latest version
  pip:
    name: "pip"
    state: "latest"
    virtualenv: "{{ ilmo_venv_path }}"
    virtualenv_command: "{{ ilmo_venv_command }}"
  become: true
  become_user: "{{ ilmo_user }}"

- name: Install gunicorn and wheel in virtualenv
  pip:
    name: ["gunicorn", "wheel", "psycopg2"]
    virtualenv: "{{ ilmo_venv_path }}"
    virtualenv_command: "{{ ilmo_venv_command }}"
  become: yes
  become_user: "{{ ilmo_user }}"

- name: Clone ILMO
  ansible.builtin.git:
    repo: "https://github.com/moan0s/ILMO2.git"
    dest: "/var/ilmo-staging/ILMO"
    version: "{{ ilmo_branch }}"
  become: yes
  become_user: "{{ ilmo_user }}"

- name: Install specified python requirements
  pip:
    virtualenv: "{{ ilmo_venv_path }}"
    virtualenv_command: "{{ ilmo_venv_command }}"
    requirements: "{{ ilmo_base_path }}/ILMO/src/requirements.txt"
  become: yes
  become_user: "{{ ilmo_user }}"

- name: Install ilmo
  pip:
    virtualenv: "{{ ilmo_venv_path }}"
    virtualenv_command: "{{ ilmo_venv_command }}"
    name: "{{ ilmo_base_path }}/ILMO/src/"
  become: yes
  become_user: "{{ ilmo_user }}"
  notify:
    - Delete static files
    - Run database migration
    - Run static file compilation

- meta: flush_handlers

- name: Enable/Start web systemd service
  systemd:
    name: "{{ ilmo_web_service_name }}"
    daemon_reload: yes
    enabled: yes
    state: started