---

- name: Check existence of ilmo service
  stat:
    path: "{{ ilmo_systemd_path }}/{{ ilmo_web_service_name }}"
  register: ilmo_web_service_stat

- name: Ensure ilmo is stopped
  service:
    name: "{{ ilmo_web_service_name }}"
    state: stopped
    enabled: false
    daemon_reload: true
  register: stopping_result
  when: "ilmo_web_service_stat.stat.exists|bool"

- name: Ensure matrix-bot-matrix-reminder-bot.service doesn't exist
  file:
    path: "{{ ilmo_systemd_path }}/{{ ilmo_web_service_name }}"
    state: absent
  when: "ilmo_web_service_stat.stat.exists|bool"

- name: Ensure systemd reloaded after matrix-bot-matrix-reminder-bot.service removal
  service:
    daemon_reload: true
  when: "ilmo_web_service_stat.stat.exists|bool"

- name: Ensure ilmo base path doesn't exist
  file:
    path: "{{ ilmo_base_path }}"
    state: absent

- name: Ensure ilmo config doesn't exist
  file:
    path: "{{ ilmo_config_path }}"
    state: absent

