---
ilmo_web_service_name: "ilmo-{{ilmo_instance_name_normalized}}.service"

ilmo_enabled: true

ilmo_user: "ilmo-{{ilmo_instance_name_normalized}}"
ilmo_group: "{{ ilmo_user }}"
ilmo_config_path: "/etc/ilmo-{{ilmo_instance_name_normalized}}"
ilmo_config_file: "{{ ilmo_config_path }}/ilmo.cfg"
ilmo_base_path: "/var/ilmo-{{ilmo_instance_name_normalized}}"
ilmo_venv_path: "{{  ilmo_base_path }}/.venv"
ilmo_data_path: "{{  ilmo_base_path }}"
ilmo_static_path: "{{  ilmo_base_path }}/static"
ilmo_venv_command: "/usr/bin/python3 -m venv"
ilmo_systemd_path: "/etc/systemd/system"

ilmo_port: 4566
ilmo_branch: main
ilmo_debug: false

ilmo_postgres_host: localhost
ilmo_database_backend: sqlite3